name: SynMfg_Code
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.10.14
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - beautifulsoup4==4.12.3
      - blenderproc==2.7.1
      - bpy==4.0.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - contourpy==1.2.1
      - cryptography==42.0.8
      - cycler==0.12.1
      - cython==3.0.10
      - filelock==3.15.4
      - fonttools==4.53.1
      - h5py==3.11.0
      - httplib2==0.22.0
      - idna==3.7
      - imageio==2.34.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - matplotlib==3.9.1
      - networkx==3.3
      - numpy==2.0.0
      - oauth2client==4.1.3
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pillow==10.4.0
      - progressbar==2.5
      - proto-plus==1.24.0
      - protobuf==5.27.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pyopenssl==24.1.0
      - pyparsing==3.1.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - requests==2.32.3
      - rsa==4.9
      - scikit-image==0.24.0
      - scipy==1.14.0
      - six==1.16.0
      - soupsieve==2.5
      - tifffile==2024.7.2
      - tqdm==4.66.4
      - uritemplate==4.1.1
      - urllib3==2.2.2
      - zstandard==0.23.0